Check that shell used for assemble.sh support <() redirection

diff --git a/src/masurca b/src/masurca
--- a/src/masurca
+++ b/src/masurca
@@ -69,6 +69,7 @@ my $CLOSE_GAPS              = 1;
 
 my $assembly_script = "assemble.sh";
 my $generate_default;
+my $skip_path_checking;
 my @prep_path;
 my @prep_ld;
 my $help;
@@ -80,11 +81,12 @@ sample configuration file can be generated with the -g switch. The
 assembly script will run the assembly proper.
 
 Options:
- -o, --output           Assembly script ($assembly_script)
- -g, --generate         Generate example configuration file
- -p, --path             Prepend to PATH in assembly script
- -l, --ld-library-path  Prepend to LD_LIBRARY_PATH in assembly script
- -h, --help             This message
+ -o, --output              Assembly script ($assembly_script)
+ -g, --generate            Generate example configuration file
+ -p, --path                Prepend to PATH in assembly script
+ -l, --ld-library-path     Prepend to LD_LIBRARY_PATH in assembly script
+     --skip-path-checking  Skip checking availability of other executables
+ -h, --help                This message
 EOS
     ;
 
@@ -184,6 +186,7 @@ GetOptions("o|output=s"          => \$assembly_script,
            "g|generate"          => \$generate_default,
            "p|path=s"            => \@prep_path,
            "l|ld-library-path=s" => \@prep_ld,
+           "skip-checking"       => \$skip_path_checking,
            "h|help"              => \$help) or die $usage;
 
 if($help) {
@@ -358,7 +361,6 @@ while(my $line=<FILE>){
 }
 die("no read data files specified") if(scalar(@pe_info_array)+scalar(@jump_info_array)+scalar(@other_info_array)==0);
 
-print "Verifying PATHS...\n";
 if(@prep_path) {
   unshift(@PATH, @prep_path);
 } else {
@@ -368,7 +370,10 @@ if(@prep_ld) {
   unshift(@LD_LIBRARY_PATH, @prep_ld);
 }
 
-&check_exec("jellyfish", "runCA", "createSuperReadsForDirectory.perl");
+unless($skip_path_checking) {
+  print "Verifying PATHS...\n";
+  &check_exec("jellyfish", "runCA", "createSuperReadsForDirectory.perl");
+}
 
 die ("no PE data specified") if(scalar(@pe_info_array)==0);
 
@@ -384,6 +389,13 @@ print FILE <<"EOS";
 # $assembly_script generated by masurca
 CONFIG_PATH="$config_abs_path"
 CMD_PATH="$cmd_abs_path"
+
+# Test that we support <() redirection
+(eval "cat <(echo test) >/dev/null" 2>/dev/null) || {
+  echo >&2 "ERROR: The shell used is missing important features."
+  echo >&2 "       Run the assembly script directly as './\$0'"
+  exit 1
+}
 
 # Parse command line switches
 while getopts ":rc" o; do
